version: "3.8"

x-gateway-template: &gateway-template
  build:
    context: .
    dockerfile: Dockerfile.gateway
  networks:
    - iot_net
  restart: unless-stopped
  depends_on:
    - hivemq
  environment:
    BUILDING_ID: "01"
    ENGINE_HOST: "engine"
  volumes:
    - ./gateway_flow.json:/data/flows.json

services:
  hivemq:
    image: hivemq/hivemq-ce:latest
    container_name: hivemq-hub
    ports:
      - "18830:1883"
      - "8883:8883"
      - "8081:8080"
    volumes:
      - ./hivemq_config.xml:/opt/hivemq/conf/config.xml
      - ./credentials.xml:/opt/hivemq/extensions/hivemq-file-rbac-extension/conf/credentials.xml
      - ./certs:/opt/hivemq/certs
    networks:
      - iot_net
    restart: always

  thingsboard:
    image: thingsboard/tb-postgres:latest
    container_name: thingsboard-cloud
    ports:
      - "9090:9090"
      - "1884:1883"
      - "5683-5688:5683-5688/udp"
    environment:
      - TB_QUEUE_TYPE=in-memory
    networks:
      - iot_net
    restart: always
    depends_on:
      - hivemq

  engine:
    build: .
    container_name: world-engine
    environment:
      - MQTT_BROKER=hivemq
      - MQTT_TLS_PORT=8883
      - PYTHONUNBUFFERED=1
    depends_on:
      - hivemq
      - gateway_f01
      - gateway_f02
      - gateway_f03
      - gateway_f04
      - gateway_f05
      - gateway_f06
      - gateway_f07
      - gateway_f08
      - gateway_f09
      - gateway_f10
    networks:
      - iot_net
    restart: unless-stopped

  subscriber:
    build: .
    container_name: world-engine-subscriber
    command: [ "python", "subscriber.py" ]
    environment:
      - MQTT_BROKER=hivemq
      - MQTT_TLS_PORT=8883
      - PYTHONUNBUFFERED=1
    depends_on:
      - hivemq
    networks:
      - iot_net
    restart: unless-stopped

  gateway_f01:
    <<: *gateway-template
    container_name: gateway_f01
    environment:
      FLOOR_ID: "1"
    ports:
      - "1881:1880"

  gateway_f02:
    <<: *gateway-template
    container_name: gateway_f02
    environment:
      FLOOR_ID: "2"
    ports:
      - "1882:1880"

  gateway_f03:
    <<: *gateway-template
    container_name: gateway_f03
    environment:
      FLOOR_ID: "3"
    ports:
      - "1885:1880"

  gateway_f04:
    <<: *gateway-template
    container_name: gateway_f04
    environment:
      FLOOR_ID: "4"
    ports:
      - "1886:1880"

  gateway_f05:
    <<: *gateway-template
    container_name: gateway_f05
    environment:
      FLOOR_ID: "5"
    ports:
      - "1887:1880"

  gateway_f06:
    <<: *gateway-template
    container_name: gateway_f06
    environment:
      FLOOR_ID: "6"
    ports:
      - "1888:1880"

  gateway_f07:
    <<: *gateway-template
    container_name: gateway_f07
    environment:
      FLOOR_ID: "7"
    ports:
      - "1889:1880"

  gateway_f08:
    <<: *gateway-template
    container_name: gateway_f08
    environment:
      FLOOR_ID: "8"
    ports:
      - "1890:1880"

  gateway_f09:
    <<: *gateway-template
    container_name: gateway_f09
    environment:
      FLOOR_ID: "9"
    ports:
      - "1891:1880"

  gateway_f10:
    <<: *gateway-template
    container_name: gateway_f10
    environment:
      FLOOR_ID: "10"
    ports:
      - "1892:1880"

networks:
  iot_net:
    driver: bridge
