version: "3.8"

services:
  hivemq:
    image: hivemq/hivemq-ce:latest
    container_name: hivemq-hub
    ports:
      - "1883:1883"
      - "8080:8080"
    networks:
      - iot_net
    restart: always

  thingsboard:
    image: thingsboard/tb-postgres:latest
    container_name: thingsboard-cloud
    ports:
      - "9090:8080"
      - "1884:1883"
      - "5683-5688:5683-5688/udp"
    environment:
      - TB_QUEUE_TYPE=in-memory
    networks:
      - iot_net
    restart: always
    depends_on:
      - hivemq

 
  engine:
    build: .
    container_name: world-engine
    environment:
      - MQTT_BROKER=hivemq
      - MQTT_PORT=1883
      - PYTHONUNBUFFERED=1
    depends_on:
      - hivemq
    networks:
      - iot_net
    restart: unless-stopped

  subscriber:
    build: .
    container_name: world-engine-subscriber
    command: [ "python", "subscriber.py" ]
    environment:
      - MQTT_BROKER=hivemq
      - MQTT_PORT=1883
      - PYTHONUNBUFFERED=1
    depends_on:
      - hivemq
    networks:
      - iot_net
    restart: unless-stopped

networks:
  iot_net:
    driver: bridge
